Apps/admSolicitudes/urls.py
from django.urls import path,re_path
from Apps.admSolicitudes import views
from django.contrib.auth.decorators import login_required
app_name = 'admSolicitudes'
urlpatterns = [
   
	path('solicitud', login_required(views.solicitud), name= "solicitud"),
     
] 

Apps/login/urls.py
from django.urls import path
from Apps.login import views
from django.contrib.auth.views import login
from Apps.login.views import registro

app_name= "registro"

urlpatterns=[
    path('accounts/login/',login,{'template_name':'login/login.html'}, name="login"),
    path('',login,{'template_name':'login/login.html'}, name="login"),
    path('registro/',registro.as_view(), name="registro_usuario"),
]

Apps/publicacion/urls.py
from django.urls import path
from Apps.publicacion import views
from django.contrib.auth.decorators import login_required

app_name = "publicacion"

urlpatterns = [
	path('registrar/', login_required(views.PublicacionCreate.as_view()), name="publicacion_registrar"),
	path('listar/', (views.listar_publicacion), name="listar_publicacion"),
	path('mostrar/<pk>/', (views.MostrarPublicacion.as_view()), name="mostrar_publicacion"),
]

chepedales/urls.py
from django.contrib import admin


from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from chepedales import views
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import LoginView,logout_then_login,LogoutView


urlpatterns = [
    path('admin', admin.site.urls),

    

    path('catalogo/',include('Apps.mainCatalogo.urls')),
    path('publicacion/', include(('Apps.publicacion.urls', 'publicacion'), namespace='publicacion')),
    
    

    
    path('administracion/',include('Apps.admSolicitudes.urls')),
    path('top/',include('Apps.top10.urls')),
    path('', include('Apps.login.urls','registro'),name='registro'),
    path('logout/',logout_then_login,name='logout'),
    


    path('Favoritos', include('Apps.top10.urls')),
    path('sitemap/', views.site_map,name="site_map"),
    path('robots.txt/', views.robots,name="robots"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="google-site-verification" content="CducxBkMmaNlGazg47p7OkTxH3fpKKaSOr6vNLIn3S4" />
        

        {%block tituloPagina%}
        <title>Chepedales</title>
        {%endblock%}
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/icono.ico'%}">
        <!--Link para archivo de plantilla-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/plantilla.min.css'%}" />

        <!--Para iconos-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css'%}" />

        {% block Bhead %}
        {% endblock %}
        {% block meta %}
        <!-- meta informacion -->
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="description" content="Pagina de informacion para pedales de guitarra"/>
            <meta name="keywords" content="guitarras,pedales,efectos,overdrive,chorus"/>
            <meta name = "robots" content="index,follow"/>
            <meta name ="author" content="Jose Flores"/>
            <meta name ="owner" content="Chepedales.INC"/>

            <!-- Open Grahp -->
            <meta property="og:url"                content="https://chepedale.herokuapp.com" />
            <meta property="og:type"               content="website" />
            <meta property="og:title"              content="Chepedales | Los mejores pedales para tu guitarra." />
            <meta property="og:description"        content="Chepedales es una pagina donde cada musico guitarrista puede dar la resena sobre sus pedales." />
            <meta property="og:image"              content="http://www.electronica-basica.com/images/pedales-guitarra.jpg" />

<!-- Twitter Card -->
    
            <meta name = "twitter: card" content = "summary_large_image" /> 
            <meta name = "twitter: site" content = "@Chepedales" />
            <meta name = "twitter: creator" content = "@Chepedales" />
            <meta name="twitter:title" content="Resenas de pedales para guitarra">
            <meta name="twitter:description" content="Chepedales es una pagina donde cada musico guitarrista puede dar la resena sobre sus pedales.">
            <meta name="twitter:image" content="https://www.guitarristas.info/foros/como-hacer-pedalera/69891"> 

            <!-- estructura de datos con json-->
            <script type='application/ld+json'> 
                {
                    "@context": "http://www.schema.org",
                    "@type": "Store",
                    "name": "Chepedales",
                    "telephone": "(+503)7700-4165",
                    "url": "http://chepedale.herokuapp.com",
                    "priceRange" : "$12 - $20",
                    "logo": "https://chepedale.herokuapp.com/static/img/logo.PNG",
                    "image": "https://chepedale.herokuapp.com/static/img/logo.PNG",
                    "description": "Chepedales es una pagina donde cada musico guitarrista puede dar la resena sobre sus pedales. ",
                    "address": {
                                "@type": "PostalAddress",
                                "streetAddress": "Chepedales@gmail.com",
                                "addressLocality": "San Salvador",
                                "addressRegion": "San Salvador",
                                "postalCode": "503",
                                "addressCountry": "El Salavador"
                                },
                    "openingHours": "Mo, Tu, We, Th, Fr 08:00-19:00 Sa 12:00-17:00",
                    "contactPoint": {
                                        "@type": "ContactPoint",
                                        "telephone": "(+503)7700-4165",
                                        "contactType": "customer service"
                                    }
                    }
                </script>


        <!-- Global site tag (gtag.js) - Google Analytics -->
                <script async src="https://www.googletagmanager.com/gtag/js?id=UA-130511500-1"></script>
                <script>
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('config', 'UA-130511500-1');
                    </script>
                    
        {% endblock %}

        
    </head>

    <body>

        <!--Menu de Navegacion-->
        <nav class="navbar navbar-expand-lg  navbar-dark bg-primary">
            <a class="navbar-brand page-scroll sticky-logo" href="{% url 'catalogo_p' %}">
            <h1><img src="{% static 'img/logo.PNG' %}" width="200" height="80"><span></span></h1>
            <a class="navbar-brand" href="{% url 'catalogo_p' %}"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-block" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link active" href="{% url 'catalogo_p' %}"><span class="icon-home"></span> Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'top' %}"><span class="icon-music"></span> Pedales favoritos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'publicacion:publicacion_registrar' %}"><span class="icon-share2"></span> Publicar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/catalogo#funcion/"><span class="icon-accessibility"></span> Nosotros</a>
                    </li>

                    {% if request.user.is_authenticated %}
                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admSolicitudes:solicitud' %}"><span class="icon-share2"></span> Solicitudes</a>
                    </li>
                    {%endif%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'catalogo_p' %}"><span class="icon-user"></span> Bienvenido: {{user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}"><span class="icon-cross"></span> Salir</a>
                    </li>
                    {%else%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registro:login' %}"><span class="icon-user"></span> Iniciar Sesión</a>
                    </li>
                    {% endif %}

                    

                </ul>

            </div>
        </nav>


        {%block body%}
        {%endblock%}

        <!--Footer-->
        {% block footer%}
        <footer>
            <div class="row p-3">
                <div class="col-lg-3" id="a">
                    <div class="alert alert-dismissible w-100 alert-danger d-inline-block">
                        <a href="https://www.instagram.com/chepedales/" class="alert-link"><span class="icon-youtube2"></span></a><strong> Instagram</strong>
                        <p>Mantente al tanto de los videos y contenido para ti.</p>
                    </div>
                </div>


                <div class="col-lg-3" id="b">
                    <div class="alert alert-dismissible w-100 alert-info d-inline-block ">
                        <a href="https://www.facebook.com/ChepeDales-575147906223895/" class="alert-link"><span class="icon-facebook"></span></a><strong> Faceebok</strong>
                        <p class="align-center">Siguenos y comparte con nostros tu pasion.</p>
                    </div>
                </div>

                <div class="col-lg-3" id="c">
                    <div class="alert alert-dismissible w-100 alert-primary d-inline-block">
                        <a href="#" class="alert-link"><span class="icon-google-plus"></span></a><strong> GooglePlus</strong>
                        <p>Comparte con la comunidad de musicos del pais.</p>
                    </div>
                </div>

                <div class="col-lg-3"id="d">
                    <div class="alert alert-dismissible w-100 alert-success d-inline-block">
                        <a href="https://twitter.com/ChepeDales" class="alert-link"><span class="icon-twitter"></span></a><strong> Twitter</strong>
                        <p>Esten pendientes, de frases celebres de musicos.</p>
                    </div>
                </div>
            </div>
            </div>
        </footer>
        {% endblock %}
    </body>


        {%block script%} {%endblock%}

    </body>

</html>