Apps/login/urls.py
from django.urls import path
from Apps.login import views
from django.contrib.auth.views import login
from Apps.login.views import registro

app_name= "registro"

urlpatterns=[
    path('accounts/login/',login,{'template_name':'login/login.html'}, name="login"),
    path('',login,{'template_name':'login/login.html'}, name="login"),
    path('registro/',registro.as_view(), name="registro_usuario"),
]

chepedales/urls.py
from django.contrib import admin


from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from chepedales import views
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import LoginView,logout_then_login,LogoutView


urlpatterns = [
    path('admin', admin.site.urls),

    

    path('catalogo/',include('Apps.mainCatalogo.urls')),
    path('publicacion/', include(('Apps.publicacion.urls', 'publicacion'), namespace='publicacion')),
    
    

    
    path('administracion/',include('Apps.admSolicitudes.urls')),
    path('top/',include('Apps.top10.urls')),
    path('', include('Apps.login.urls','registro'),name='registro'),
    path('logout/',logout_then_login,name='logout'),
    


    path('Favoritos', include('Apps.top10.urls')),
    path('sitemap/', views.site_map,name="site_map"),
    path('robots.txt/', views.robots,name="robots"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps/login/models.py
from django.db import models

# Create your models here

Apps/login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class Registrar(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'Correo',
        }

Apps/login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import CreateView
from Apps.login.forms import Registrar

# Create your views here.




class registro(CreateView):
    model = User
    template_name = 'login/login.html'
    form_class = Registrar
    success_url = reverse_lazy('publicacion:publicacion_registrar')
    

templates/login/login.html
{% extends 'base/base.html' %}
{%load staticfiles%}

<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block tituloPagina%}
        <title>Chepedales | Login</title>
        {%endblock%}

        {% block Bhead %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{%static 'css/login.css' %}" />
        {% endblock %}
        <meta name="google-site-verification" content="CducxBkMmaNlGazg47p7OkTxH3fpKKaSOr6vNLIn3S4" />


    </head>
    {%block body%}
    {% if request.path == '/registro/'%}

    <body class="bg-dark" onload="document.getElementById('t').click() "></body>
    {%else%}

    <body class="bg-dark">
        <div class="alert alert-primary text-center alert-dismissible fade show mb-0" role="alert">
            <strong>Bienvenido! Ingrese datos de Inicio de Sesion, para Confirmar.</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {%endif%}

        <div class="row">
            <div class="col-lg-9">
                <!--Carusel-->
                <div class="carousel slide" data-ride="carousel" id="carusel">
                    <ol class="carousel-indicators">
                        <li class="active" data-slide-to="0" data-target="#carusel">
                        </li>
                        <li data-slide-to="1" data-target="#carusel">
                        </li>
                        <li data-slide-to="2" data-target="#carusel">
                        </li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active" style="height: 100vh">
                            <img alt="First Slide" class="d-block h-100 w-100" src="{% static 'img/slide0.jpg' %}">

                            <div class="carousel-caption d-none d-md-block">
                                <h2 class="h1">
                                    Vive la pasion de la musica
                                </h2>
                                <p>
                                    Todo lo que necesitas en CHEPEDALES.
                                </p>
                            </div>
                        </div>
                        <div class="carousel-item" style="height: 100vh">
                            <img alt="Second slide" class="d-block img-responsive" src="{% static 'img/slide1.jpg' %}">
                            <div class="carousel-caption d-none d-md-block">
                                <h1>
                                    Pedales
                                </h1>
                                <p>
                                    <b>
                                        Videos, tips y articulos acerca de lo que amas.
                                    </b>
                                </p>
                            </div>
                        </div>
                        <div class="carousel-item " style="height:100vh">
                            <img alt="Third slide" class="d-block h-100 w-100" id="tercero" src="{% static 'img/slide2.jpg' %}">
                            <div class="carousel-caption d-none d-md-block">
                                <h1>
                                    CHEPEDALES
                                </h1>
                                <p color="black">
                                    <b>
                                        Comparte contenido con otros amantes de la musica y de los efectos.
                                    </b>
                                </p>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" data-slide="prev" href="#carusel" role="button">
                        <span aria-hidden="true" class="carousel-control-prev-icon">
                        </span>
                        <span class="sr-only">
                            Anterior
                        </span>
                    </a>
                    <a class="carousel-control-next" data-slide="next" href="#carusel" role="button">
                        <span aria-hidden="true" class="carousel-control-next-icon">
                        </span>
                        <span class="sr-only">
                            Siguiente
                        </span>
                    </a>
                </div>
            </div>

            <!--Formulario para autenticacion-->

            <div class="col-lg-3" id="prueba">
                <div class="row">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="login-box col-xl-12 text-center" style="height:100vh">
                            <!--<img src="{%static 'img/user.png' %}" class="avatar">-->
                            <span class="icon-user display-1"></span>
                            <h2 class="h3">Iniciar Sesion</h2>
                            <p>Usuario</p>
                            <input id="username" type="text" name="username" placeholder="Introduzca su ID">
                            <p>Password</p>
                            <input id="password" type="password" name="password" placeholder="Introduzca el password">

                            {% if request.path == '/registro/'%}
                            <button id="btn" class="btn btn-warning btn-block" type="button" onclick="mas()">Iniciar
                                Sesion</button>

                            <button id="btn" class="btn btn-warning btn-block" type="submit" name="button" hidden="hidden">Iniciar
                                Sesion</button>

                            {%else%}
                            <button id="btn" class="btn btn-warning btn-block" type="submit" name="button">Iniciar
                                Sesion</button>
                            {%endif%}


                            <button id="btn" class="btn btn-warning btn-block" type="button" onclick="document.getElementById('a').click() ">Registrarse</button>

                            <button id="t" type="button" data-toggle="modal" data-target="#registro" hidden="true"></button>

                            <a href="{% url 'registro:registro_usuario' %}" hidden="true" id="a"></a>

                        </div>
                    </form>
                </div>
                <!-- Formulario para registro de usuario-->

                <!-- Modal -->
                <div class="modal fade" id="registro" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">Ingrese los Datos</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <!--Cuerpo del modal-->
                                <form method="POST">
                                    {% csrf_token %}

                                    <label>Nombre:</label>
                                    <input class="form-control" name="first_name">
                                    <label>Apellidos:</label>
                                    <input class="form-control" name="last_name">
                                    <label>Nombre de Usuario:</label>
                                    <input class="form-control" name="username" id="user">
                                    <label>Correo Electronico:</label>
                                    <input class="form-control" type="email" name="email">
                                    <label>Contraseña: </label>
                                    <input class="form-control" type="password" name="password1" id="pass">
                                    <label>Confirmar Contraseña:</label>
                                    <input class="form-control" type="password" name="password2">

                                    <button type="submit" class="btn btn-primary" id="r" hidden="true">Guardar</button>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                <button type="button" class="btn btn-primary" onclick="capturar()">Registrar</button>
                                <a href="{% url 'registro:login' %}" hidden="true" id="l"></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.bundle.js' %}" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>

        <script type="text/javascript">
            function capturar() {
                document.getElementById("r").click();
            }

            function mas() {
                document.getElementById("l").click();
            }
        </script>
    </body>
    {%endblock%}

</html>